import duckdb

duck_conn = duckdb.connect(r"D:\temp\GEOM90008_DB.duckdb")

# Enable spatial and postgres extension in DuckDB
duck_conn.execute("INSTALL spatial;")
duck_conn.execute("LOAD spatial;")
duck_conn.execute("INSTALL postgres;")
duck_conn.execute("LOAD postgres;")

# Attach Postgres DB in DuckDB
duck_conn.execute("ATTACH 'dbname=geom90008 user=hhhosseini password=H@mid3756537565#@ host=wammawatcha.its.unimelb.edu.au port=5432' AS pg (TYPE postgres);")

duck_conn.execute("CREATE TABLE branches AS SELECT * FROM pg.spatial.branches;")
duck_conn.execute("CREATE TABLE carlton_edges AS SELECT * FROM pg.spatial.carlton_edges;")
duck_conn.execute("CREATE TABLE carlton_nodes AS SELECT * FROM pg.spatial.carlton_nodes;")
duck_conn.execute("CREATE TABLE ptv_train_corridor_centreline AS SELECT * FROM pg.spatial.ptv_train_corridor_centreline;")
duck_conn.execute("CREATE TABLE ptv_train_track_centreline AS SELECT * FROM pg.spatial.ptv_train_track_centreline;")
duck_conn.execute("CREATE TABLE unimelb_campus AS SELECT * FROM pg.spatial.unimelb_campus;")
duck_conn.execute("CREATE TABLE us_cities AS SELECT * FROM pg.spatial.us_cities;")
duck_conn.execute("CREATE TABLE us_counties AS SELECT * FROM pg.spatial.us_counties;")
duck_conn.execute("CREATE TABLE us_interstates AS SELECT * FROM pg.spatial.us_interstates;")
duck_conn.execute("CREATE TABLE us_restaurants AS SELECT * FROM pg.spatial.us_restaurants;")
duck_conn.execute("CREATE TABLE us_rivers AS SELECT * FROM pg.spatial.us_rivers;")
duck_conn.execute("CREATE TABLE us_states AS SELECT * FROM pg.spatial.us_states;")
duck_conn.execute("CREATE TABLE us_states_multisurface AS SELECT * FROM pg.spatial.us_states_multisurface;")
duck_conn.execute("CREATE TABLE victoria_lgas AS SELECT * FROM pg.spatial.victoria_lgas;")
duck_conn.execute("CREATE TABLE victoria_police_stations AS SELECT * FROM pg.spatial.victoria_police_stations;")
# duck_conn.execute("CREATE TABLE victoria_roads2023 AS SELECT * FROM pg.spatial.victoria_roads2023;")
duck_conn.execute("CREATE TABLE world_continents AS SELECT * FROM pg.spatial.world_continents;")
duck_conn.execute("CREATE TABLE world_countries AS SELECT * FROM pg.spatial.world_countries_new;")

duck_conn.execute("ALTER TABLE branches RENAME COLUMN location to location_;")
duck_conn.execute("ALTER TABLE carlton_edges RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE carlton_nodes RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE ptv_train_corridor_centreline RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE ptv_train_track_centreline RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE unimelb_campus RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE us_cities RENAME COLUMN location to location_;")
duck_conn.execute("ALTER TABLE us_counties RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE us_interstates RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE us_restaurants RENAME COLUMN location to location_;")
duck_conn.execute("ALTER TABLE us_rivers RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE us_states RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE us_states_multisurface RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE victoria_lgas RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE victoria_police_stations RENAME COLUMN geom to geom_;")
# duck_conn.execute("ALTER TABLE victoria_roads2023 RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE world_continents RENAME COLUMN geom to geom_;")
duck_conn.execute("ALTER TABLE world_countries RENAME COLUMN geom to geom_;")

duck_conn.execute("ALTER TABLE branches ADD COLUMN location GEOMETRY;")
duck_conn.execute("ALTER TABLE carlton_edges ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE carlton_nodes ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE ptv_train_corridor_centreline ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE ptv_train_track_centreline ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE unimelb_campus ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE us_cities ADD COLUMN location GEOMETRY;")
duck_conn.execute("ALTER TABLE us_counties ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE us_interstates ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE us_restaurants ADD COLUMN location GEOMETRY;")
duck_conn.execute("ALTER TABLE us_rivers ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE us_states ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE us_states_multisurface ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE victoria_lgas ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE victoria_police_stations ADD COLUMN geom GEOMETRY;")
# duck_conn.execute("ALTER TABLE victoria_roads2023 ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE world_continents ADD COLUMN geom GEOMETRY;")
duck_conn.execute("ALTER TABLE world_countries ADD COLUMN geom GEOMETRY;")

duck_conn.execute("ALTER TABLE branches ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE carlton_edges ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE carlton_nodes ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE ptv_train_corridor_centreline ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE ptv_train_track_centreline ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE unimelb_campus ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_cities ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_counties ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_interstates ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_restaurants ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_rivers ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_states ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE us_states_multisurface ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE victoria_lgas ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE victoria_police_stations ADD COLUMN srid INTEGER;")
# duck_conn.execute("ALTER TABLE victoria_roads2023 ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE world_continents ADD COLUMN srid INTEGER;")
duck_conn.execute("ALTER TABLE world_countries ADD COLUMN srid INTEGER;")

duck_conn.execute("UPDATE branches SET location = ST_GeomFromWKB(location_);")
duck_conn.execute("UPDATE carlton_edges SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE carlton_nodes SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE ptv_train_corridor_centreline SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE ptv_train_track_centreline SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE unimelb_campus SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE us_cities SET location = ST_GeomFromWKB(location_);")
duck_conn.execute("UPDATE us_counties SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE us_interstates SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE us_restaurants SET location = ST_GeomFromWKB(location_);")
duck_conn.execute("UPDATE us_rivers SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE us_states SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE us_states_multisurface SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE victoria_lgas SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE victoria_police_stations SET geom = ST_GeomFromWKB(geom_);")
# duck_conn.execute("UPDATE victoria_roads2023 SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE world_continents SET geom = ST_GeomFromWKB(geom_);")
duck_conn.execute("UPDATE world_countries SET geom = ST_GeomFromWKB(geom_);")

duck_conn.execute("UPDATE branches SET srid = 4326;")
duck_conn.execute("UPDATE carlton_edges SET srid = 4326;")
duck_conn.execute("UPDATE carlton_nodes SET srid = 4327;")
duck_conn.execute("UPDATE ptv_train_corridor_centreline SET srid = 7844;")
duck_conn.execute("UPDATE ptv_train_track_centreline SET srid = 7844;")
duck_conn.execute("UPDATE unimelb_campus SET srid = 7899;")
duck_conn.execute("UPDATE us_cities SET srid = 4326;")
duck_conn.execute("UPDATE us_counties SET srid = 4326;")
duck_conn.execute("UPDATE us_interstates SET srid = 4326;")
duck_conn.execute("UPDATE us_restaurants SET srid = 4326;")
duck_conn.execute("UPDATE us_rivers SET srid = 4326;")
duck_conn.execute("UPDATE us_states SET srid = 4326;")
duck_conn.execute("UPDATE us_states_multisurface SET srid = 4326;")
duck_conn.execute("UPDATE victoria_lgas SET srid = 4283;")
duck_conn.execute("UPDATE victoria_police_stations SET srid = 7899;")
# duck_conn.execute("UPDATE victoria_roads2023 SET srid = 7899;")
duck_conn.execute("UPDATE world_continents SET srid = 4326;")
duck_conn.execute("UPDATE world_countries SET srid = 4326;")

duck_conn.execute("ALTER TABLE branches DROP COLUMN location_;")
duck_conn.execute("ALTER TABLE carlton_edges DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE carlton_nodes DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE ptv_train_corridor_centreline DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE ptv_train_track_centreline DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE unimelb_campus DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE us_cities DROP COLUMN location_;")
duck_conn.execute("ALTER TABLE us_counties DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE us_interstates DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE us_restaurants DROP COLUMN location_;")
duck_conn.execute("ALTER TABLE us_rivers DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE us_states DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE us_states_multisurface DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE victoria_lgas DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE victoria_police_stations DROP COLUMN geom_;")
# duck_conn.execute("ALTER TABLE victoria_roads2023 DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE world_continents DROP COLUMN geom_;")
duck_conn.execute("ALTER TABLE world_countries DROP COLUMN geom_;")

print(duck_conn.execute("DESCRIBE branches;").fetchall())
# print(duck_conn.execute("select * from branches").fetchall())
