project:
  type: website

website:
  title: "HamidSDMTestWeb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Home
      - href: P4_logical.qmd
        text: Home
      - href: P6_geometrical.qmd
        text: Home
      - href: P8_network.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



