project:
  type: website

website:
  title: "HamidSDMTestWeb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Home
      - href: [P4]logical.qmd
        text: Home
      - href: [P6]geometrical.qmd
        text: Home
      - href: [P8]network.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



